"""initial schema

Revision ID: b17e0258643f
Revises: 
Create Date: 2026-05-10 15:28:20.022643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17e0258643f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_category', sa.String(length=100), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_sessions_user_score', 'interview_sessions', ['user_id', 'overall_score'], unique=False)
    op.create_index('ix_interview_sessions_user_started', 'interview_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('progress_tracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date_recorded', sa.DateTime(), nullable=False),
    sa.Column('rolling_average_score', sa.Float(), nullable=False),
    sa.Column('total_interviews', sa.Integer(), nullable=False),
    sa.Column('most_improved_category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_progress_tracking_user_date', 'progress_tracking', ['user_id', 'date_recorded'], unique=False)
    op.create_table('analytics_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_scores_session', 'analytics_scores', ['session_id'], unique=False)
    op.create_table('question_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_asked', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_history_session', 'question_history', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_history_session', table_name='question_history')
    op.drop_table('question_history')
    op.drop_index('ix_analytics_scores_session', table_name='analytics_scores')
    op.drop_table('analytics_scores')
    op.drop_index('ix_progress_tracking_user_date', table_name='progress_tracking')
    op.drop_table('progress_tracking')
    op.drop_index('ix_interview_sessions_user_started', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_user_score', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
